name: DVC Tracking with Github Actions
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: Running_updates
        env: 
          GH_TOKEN: ${{ github.token }}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          make install 
          dvc repro
          git fetch --prune
          dvc metrics diff --show-md master > report.md
          git config --global --add safe.directory /__w/dvc_pipeline_tracking/dvc_pipeline_tracking
          # Add figure to the report
          echo "## Validating results by region"
          echo '![](./by_region.png "Region wise plot")' >> report.md
          cml comment create report.md
          
